title: Site
icon: globe

tabs:
  content:
    label:
      en: Content
      de: Inhalt
      fr: Contenu
    icon: text
    columns:
      - width: 1/3
        sections:
          info:
            headline:
              en: Information
              de: Information
              fr: Information
            type: info
            theme: none
            text:
              en: "This Website is designed and built by (link:https://matthiaswyler.com text: Matthias Wyler). For help don't hesitate and write an (email: mail@matthiaswyler.com text: email). Please double-check the licenses and sources of all images before you upload them to the website."
              de: "Diese Website wurde von (link:https://matthiaswyler.com  text: Matthias Wyler) entworfen und programmiert. Für Hilfe zögere nicht und schreib mir ein (email: mail@matthiaswyler.com text: E-Mail). Bitte überprüf die Lizenzen und Quellen aller Bilder, bevor du sie auf die Website hochladen."
              fr: "Ce site Web a été conçu et construit par (link:https://matthiaswyler.com text: Matthias Wyler). Pour obtenir de l'aide, n'hésitez pas à écrire un (email: mail@matthiaswyler.com). Veuillez vérifier les licences et les sources de toutes les images avant de les télécharger sur le site Web."
      - width: 2/3
        sections:
          pages:
            label:
              en: All published Pages
              de: Alle veröffentlichten Seiten
              fr: Toutes les pages publiées
            type: pages
            status: listed
            template:
              - life
              - resource
              - books
              - manifesto
              - default
              - home
              - error
              - imprint
              - privacy
              - newsletter
            image: icon
          unpublished:
            label:
              en: Unpublished Pages
              de: Unveröffentlichte Seiten
              fr: Pages non publiées
            type: pages
            status: unlisted
          work:
            label:
              en: Work
              de: Arbeit
              fr: Travail
            type: pages
            parent: site.find('projects')
            layout: cardlets
            status: listed
            image:
              query: page.cover.toFile
              cover: true
              ratio: 1/1
            limit: 6
            info: "{{ page.published.toDate('d.m.Y') }}"

  seo: seo/site
